<?php 
/** 
* @var \Magento\Theme\Block\Html\Header\Logo $block 
*/ 
?> 
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?> 
<div class="ttr_header_element_alignment container">
<div class="ttr_header_logo">
<?php if ($block->isHomePage()):?> 
<strong class="logo"><?php else: ?> <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>"> <?php endif ?><img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>" class="" alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>" <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?> <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?> /><?php if ($block->isHomePage()):?></strong><?php else:?></a><?php endif?></div>
</div>
