<span class="product-image-container"
      style="width:<?php echo is_numeric($block->getWidth()) ? $block->getWidth() : 0; ?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?php echo is_numeric($block->getRatio()) ? ($block->getRatio() * 100) : 0; ?>%;">
        <img class="product-image-photo"
             <?php
             // Kiểm tra nếu getCustomAttributes trả về mảng
             if (is_array($block->getCustomAttributes())) {
                 echo implode(' ', array_map('htmlspecialchars', $block->getCustomAttributes()));
             } else {
                 echo htmlspecialchars($block->getCustomAttributes(), ENT_QUOTES, 'UTF-8');
             }
             ?>
             src="<?php echo htmlspecialchars($block->getImageUrl(), ENT_QUOTES, 'UTF-8'); ?>"
             width="<?php echo is_numeric($block->getResizedImageWidth()) ? $block->getResizedImageWidth() : 0; ?>"
             height="<?php echo is_numeric($block->getResizedImageHeight()) ? $block->getResizedImageHeight() : 0; ?>"
             alt="<?php echo htmlspecialchars($block->stripTags($block->getLabel(), null, true), ENT_QUOTES, 'UTF-8'); ?>"/></span>
</span>
