<?php $h=  $this->getRequest()->getFullActionName(); if($h == 'cms_index_index'){?>
<div class="margin_collapsetop"></div>
<div id="ttr_slideshow_inner">
<ul>
<li id="Slide0" class="ttr_slide" data-slideEffect="Fade">
<a href="http://templatetoaster.com/"></a>
<div class="ttr_slideshow_last">
<div class="ttr_slideshow_element_alignment container" data-begintime="0" data-effect="Fade" data-easing="linear" data-slide="None" data-duration="0">
</div>
<div class="ttr_slideshowshape01" data-effect="Fade" data-begintime="0" data-duration="1" data-easing="linear" data-slide="left">
<div class="html_content"><p style="margin:30px 0px 5px 0px;text-align:Center;"><span style="font-weight:700;font-size:4em;color:rgba(255,255,0,1);">Instead of sugary desserts</span><span style="font-weight:700;font-size:4em;color:rgba(255,255,0,1);"> </span><span style="font-weight:700;font-size:4em;color:rgba(255,255,0,1);">get some fruity treats</span></p><p style="margin:30px 0px 5px 0px;text-align:Center;"><span><a href="http://templatetoaster.com" target="_self" class="btn btn-lg btn-info">Order Now</a></span></p></div>
</div>
</div>
</li>
<li id="Slide1" class="ttr_slide" data-slideEffect="Fade">
<a href="http://templatetoaster.com/"></a>
<div class="ttr_slideshow_last">
<div class="ttr_slideshow_element_alignment container" data-begintime="0" data-effect="Fade" data-easing="linear" data-slide="None" data-duration="0">
</div>
<a href="" class="slideshowforeground11" target="_self" data-effect="Fade" data-begintime="0" data-duration="1" data-easing="linear" data-slide="None">
</a>
<div class="ttr_slideshowshape11" data-effect="Fade" data-begintime="0" data-duration="1" data-easing="linear" data-slide="left">
<div class="html_content"><p style="margin:30px 0px 5px 0px;text-align:Center;"><span style="font-weight:700;font-size:4em;color:rgba(255,255,0,1);">You are what you eat</span></p><p style="margin:0px 0px 5px 0px;text-align:Center;"><span style="font-weight:700;font-size:4em;color:rgba(255,255,0,1);">So</span><span style="font-weight:700;font-size:4em;color:rgba(255,255,0,1);"> </span><span style="font-weight:700;font-size:4em;color:rgba(255,255,0,1);">Eat fresh and stay refreshed</span></p><p style="margin:0px 0px 5px 0px;text-align:Center;"><span><a href="http://templatetoaster.com" target="_self" class="btn btn-lg btn-info">Order Now</a></span></p></div>
</div>
</div>
</li>
<li id="Slide2" class="ttr_slide" data-slideEffect="Fade">
<a href="http://templatetoaster.com/"></a>
<div class="ttr_slideshow_last">
<div class="ttr_slideshow_element_alignment container" data-begintime="0" data-effect="Fade" data-easing="linear" data-slide="None" data-duration="0">
</div>
<div class="ttr_slideshowshape21" data-effect="Fade" data-begintime="0" data-duration="1" data-easing="linear" data-slide="left">
<div class="html_content"><p style="margin:30px 0px 5px 0px;text-align:Center;"><span style="font-weight:700;font-size:4em;color:rgba(255,255,0,1);">A healthy outside</span></p><p style="margin:0px 0px 5px 0px;text-align:Center;"><span style="font-weight:700;font-size:4em;color:rgba(255,255,0,1);">Starts from the inside</span></p><p style="margin:30px 0px 5px 0px;text-align:Center;"><span><a href="http://templatetoaster.com" target="_self" class="btn btn-lg btn-info">Order Now</a></span></p></div>
</div>
</div>
</li>
</ul>
</div>
<div class="ttr_slideshow_in">
<div class="ttr_slideshow_last">
<div id="nav"></div>
<div class="ttr_slideshow_logo">
</div>
</div>
</div>
<?php } ?>
